 var name="harikrishna"
 console.log(name.length)
 console.log(name[0])
 console.log(name[1])
 console.log(name[2])
 console.log(name[3])
 console.log(name[4])
 console.log(name[5])
 console.log(name[6])
 console.log(name[7])
 console.log(name[8])
 console.log(name[9])
 console.log(name[10])
 console.log(name[12])
 let fname="vijay"
 console.log(`my name is ${name} and his friends name is ${fname}`)
 console.log(fname.toUpperCase([0]));
console.log(fname.toLowerCase([1,2,3,4]));
console.log(fname.slice(1 ,4))
console.log("my name is harikrishna\n and i love coding")
console.log(fname.length)
console.log(name.slice(1,5))
console.log(name.slice(1,-1))
console.log(fname.replace("vijay","00000000"))
console.log(fname.concat(" virat"))
